import SwiftUI

/// The "AI" tab: enable LLM autocompletion, choose the active provider, and
/// manage providers (each with its own API key, stored in the Keychain).
struct AISettingsView: View {
    @ObservedObject private var store = ProviderStore.shared
    @State private var editing: ProviderProfile?
    @State private var isNew = false

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    Toggle("Enable AI Completion", isOn: Binding(
                        get: { store.isEnabled },
                        set: { store.setEnabled($0) }
                    ))
                } footer: {
                    Text("Suggestions are generated by your chosen LLM provider using your recent commands and the visible terminal text. Input is sent to that provider.")
                }

                if !store.profiles.isEmpty {
                    Section("Active Provider") {
                        Picker("Provider", selection: Binding(
                            get: { store.selectedProviderID ?? store.profiles.first?.id ?? "" },
                            set: { store.select($0) }
                        )) {
                            ForEach(store.profiles) { profile in
                                Text(profile.name).tag(profile.id)
                            }
                        }
                        if let active = store.activeProvider, !store.isReady, store.isEnabled {
                            Label("Add an API key for \(active.name) to enable completions.", systemImage: "exclamationmark.triangle")
                                .font(.footnote)
                                .foregroundStyle(.orange)
                        }
                    }
                }

                Section("Providers") {
                    ForEach(store.profiles) { profile in
                        Button {
                            isNew = false
                            editing = profile
                        } label: {
                            VStack(alignment: .leading, spacing: 2) {
                                Text(profile.name).foregroundStyle(.primary)
                                Text("\(profile.kind.title) · \(profile.model)")
                                    .font(.subheadline).foregroundStyle(.secondary)
                            }
                        }
                        .swipeActions(edge: .trailing) {
                            Button(role: .destructive) { store.delete(profile) } label: {
                                Label("Delete", systemImage: "trash")
                            }
                        }
                    }

                    Menu {
                        ForEach(ProviderProfile.presets()) { preset in
                            Button(preset.name) { addProvider(from: preset) }
                        }
                        Divider()
                        Button("Custom…") {
                            addProvider(from: ProviderProfile(
                                name: "Custom", kind: .openAICompatible,
                                baseURL: "https://", chatEndpoint: "/v1/chat/completions", model: ""
                            ))
                        }
                    } label: {
                        Label("Add Provider", systemImage: "plus")
                    }
                }
            }
            .navigationTitle("AI")
            .sheet(item: $editing) { profile in
                ProviderEditView(profile: profile, isNew: isNew)
            }
        }
    }

    private func addProvider(from preset: ProviderProfile) {
        // Fresh id so the same preset can be added more than once.
        isNew = true
        editing = ProviderProfile(
            name: preset.name, kind: preset.kind, baseURL: preset.baseURL,
            chatEndpoint: preset.chatEndpoint, model: preset.model,
            extraHeadersJSON: preset.extraHeadersJSON
        )
    }
}

/// Edit (or create) a single provider, set its API key, and test connectivity.
private struct ProviderEditView: View {
    @Environment(\.dismiss) private var dismiss
    @ObservedObject private var store = ProviderStore.shared

    @State private var profile: ProviderProfile
    @State private var apiKey: String = ""
    @State private var testing = false
    @State private var testResult: String?
    @State private var testOK = false
    private let isNew: Bool

    init(profile: ProviderProfile, isNew: Bool) {
        _profile = State(initialValue: profile)
        self.isNew = isNew
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("Name") {
                    TextField("Name", text: $profile.name)
                        .autocorrectionDisabled()
                }
                Section("API") {
                    Picker("Kind", selection: $profile.kind) {
                        ForEach(ProviderKind.allCases) { kind in
                            Text(kind.title).tag(kind)
                        }
                    }
                    LabeledField("Base URL", text: $profile.baseURL)
                    LabeledField("Endpoint", text: $profile.chatEndpoint)
                    LabeledField("Model", text: $profile.model)
                }
                Section("API Key") {
                    SecureField("API key", text: $apiKey)
                        .autocorrectionDisabled()
                        .textInputAutocapitalization(.never)
                }
                Section {
                    Button {
                        Task { await runTest() }
                    } label: {
                        HStack {
                            Text("Test Connection")
                            Spacer()
                            if testing { ProgressView() }
                        }
                    }
                    .disabled(testing || profile.model.isEmpty)
                    if let result = testResult {
                        Label(result, systemImage: testOK ? "checkmark.circle" : "xmark.circle")
                            .font(.footnote)
                            .foregroundStyle(testOK ? .green : .red)
                    }
                }
            }
            .navigationTitle(isNew ? "Add Provider" : "Edit Provider")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        store.save(profile, apiKey: apiKey)
                        dismiss()
                    }
                    .disabled(profile.name.isEmpty || profile.model.isEmpty)
                }
            }
            .onAppear {
                if apiKey.isEmpty { apiKey = store.apiKey(for: profile.id) ?? "" }
            }
        }
    }

    private func runTest() async {
        testing = true
        testResult = nil
        let client = HTTPProviderClient(profile: profile, apiKey: apiKey)
        let request = LLMRequest(
            model: profile.model,
            systemPrompt: "You are a connectivity test. Reply with OK only.",
            userPrompt: "Reply with OK.",
            temperature: 0,
            maxTokens: 16
        )
        do {
            let response = try await client.complete(request)
            testOK = true
            testResult = "OK · \(response.text.prefix(40))"
        } catch {
            testOK = false
            testResult = (error as? LLMProviderError)?.errorDescription ?? error.localizedDescription
        }
        testing = false
    }
}

/// A label + trailing text field row with terminal-friendly input traits.
private struct LabeledField: View {
    let label: String
    @Binding var text: String

    init(_ label: String, text: Binding<String>) {
        self.label = label
        _text = text
    }

    var body: some View {
        HStack {
            Text(label).foregroundStyle(.secondary)
            Spacer()
            TextField(label, text: $text)
                .multilineTextAlignment(.trailing)
                .autocorrectionDisabled()
                .textInputAutocapitalization(.never)
        }
    }
}
